In [1]:
from typing import Sequence, Tuple, TypeVar
import nltk
from nltk.corpus import brown
import numpy as np

Q = TypeVar("Q")
V = TypeVar("V")

In [2]:
corpus = nltk.corpus.brown.tagged_sents(tagset="universal")[:10000]
corpus

[[('The', 'DET'), ('Fulton', 'NOUN'), ('County', 'NOUN'), ('Grand', 'ADJ'), ('Jury', 'NOUN'), ('said', 'VERB'), ('Friday', 'NOUN'), ('an', 'DET'), ('investigation', 'NOUN'), ('of', 'ADP'), ("Atlanta's", 'NOUN'), ('recent', 'ADJ'), ('primary', 'NOUN'), ('election', 'NOUN'), ('produced', 'VERB'), ('``', '.'), ('no', 'DET'), ('evidence', 'NOUN'), ("''", '.'), ('that', 'ADP'), ('any', 'DET'), ('irregularities', 'NOUN'), ('took', 'VERB'), ('place', 'NOUN'), ('.', '.')], [('The', 'DET'), ('jury', 'NOUN'), ('further', 'ADV'), ('said', 'VERB'), ('in', 'ADP'), ('term-end', 'NOUN'), ('presentments', 'NOUN'), ('that', 'ADP'), ('the', 'DET'), ('City', 'NOUN'), ('Executive', 'ADJ'), ('Committee', 'NOUN'), (',', '.'), ('which', 'DET'), ('had', 'VERB'), ('over-all', 'ADJ'), ('charge', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('election', 'NOUN'), (',', '.'), ('``', '.'), ('deserves', 'VERB'), ('the', 'DET'), ('praise', 'NOUN'), ('and', 'CONJ'), ('thanks', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('City

In [3]:
tagged_corpus = nltk.corpus.brown.tagged_sents(tagset="universal")[:10_000]
tagged_corpus

[[('The', 'DET'), ('Fulton', 'NOUN'), ('County', 'NOUN'), ('Grand', 'ADJ'), ('Jury', 'NOUN'), ('said', 'VERB'), ('Friday', 'NOUN'), ('an', 'DET'), ('investigation', 'NOUN'), ('of', 'ADP'), ("Atlanta's", 'NOUN'), ('recent', 'ADJ'), ('primary', 'NOUN'), ('election', 'NOUN'), ('produced', 'VERB'), ('``', '.'), ('no', 'DET'), ('evidence', 'NOUN'), ("''", '.'), ('that', 'ADP'), ('any', 'DET'), ('irregularities', 'NOUN'), ('took', 'VERB'), ('place', 'NOUN'), ('.', '.')], [('The', 'DET'), ('jury', 'NOUN'), ('further', 'ADV'), ('said', 'VERB'), ('in', 'ADP'), ('term-end', 'NOUN'), ('presentments', 'NOUN'), ('that', 'ADP'), ('the', 'DET'), ('City', 'NOUN'), ('Executive', 'ADJ'), ('Committee', 'NOUN'), (',', '.'), ('which', 'DET'), ('had', 'VERB'), ('over-all', 'ADJ'), ('charge', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('election', 'NOUN'), (',', '.'), ('``', '.'), ('deserves', 'VERB'), ('the', 'DET'), ('praise', 'NOUN'), ('and', 'CONJ'), ('thanks', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('City

In [ ]:
tagged_corpus2 = nltk.corpus.brown.tagged_sents(tagset="universal")[:5]
tagged_corpus2

In [10]:
### fun to count repeated elements in list
def count_ngrams(lst):
    element_count = {}
    for item in lst:
        if item in element_count:
            element_count[item] += 1
        else:
            element_count[item] = 1
    return element_count

In [21]:
POS_list = []
for i in tagged_corpus2:
    POS_list += [tup[1] for tup in i]

In [22]:
POS_counts = count_ngrams(POS_list)
list_pos = list(POS_counts.keys())
list_counts_pos = list(POS_counts.values())
ts = sum(list_counts_pos)
pi = [c / ts for c in list_counts_pos]

In [ ]:
print(POS_list)
print(POS_counts)
print("orden pi:", list_pos)
print(list_counts_pos)
print(pi)
print("suma de probs en pi:", sum(pi))

In [94]:
# matrix a

## build dict of transition counts
# function to build bigrams
n_grams = [tuple(POS_list[i : i + 2]) for i in range(len(POS_list) - 1)]
# function to count bigrams, stores tuple of bigram as keys and repetition count as value---
d_pos_counts = count_ngrams(n_grams)
d_pos_counts

## build matrix
# build cols for matrix according to order of pi
unique_pos2 = list_pos
# build empty matix with rows and cols using pos order from pi
matrix = np.zeros((len(unique_pos2), len(unique_pos2)))
# Populate the matrix with values from the dictionary
for (pos1, pos2), count in d_pos_counts.items():
    matrix[unique_pos2.index(pos1)][unique_pos2.index(pos2)] = count

# Display the matrix
print(unique_pos2)
print(matrix)

['DET', 'NOUN', 'ADJ', 'VERB', 'ADP', '.', 'ADV', 'CONJ', 'PRT', 'PRON']
[[ 1. 18.  3.  2.  0.  0.  0.  0.  0.  0.]
 [ 2. 13.  4.  8. 11. 10.  1.  3.  1.  0.]
 [ 0.  9.  0.  0.  1.  2.  0.  2.  0.  0.]
 [ 1.  3.  2.  6.  4.  4.  0.  0.  0.  1.]
 [10.  7.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 7.  1.  0.  2.  4.  6.  1.  0.  0.  0.]
 [ 1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]
