In [1]:
from typing import Sequence, Tuple, TypeVar
import nltk
from nltk.corpus import brown
import numpy as np

Q = TypeVar("Q")
V = TypeVar("V")

In [2]:
corpus = nltk.corpus.brown.tagged_sents(tagset="universal")[:10000]
corpus

[[('The', 'DET'), ('Fulton', 'NOUN'), ('County', 'NOUN'), ('Grand', 'ADJ'), ('Jury', 'NOUN'), ('said', 'VERB'), ('Friday', 'NOUN'), ('an', 'DET'), ('investigation', 'NOUN'), ('of', 'ADP'), ("Atlanta's", 'NOUN'), ('recent', 'ADJ'), ('primary', 'NOUN'), ('election', 'NOUN'), ('produced', 'VERB'), ('``', '.'), ('no', 'DET'), ('evidence', 'NOUN'), ("''", '.'), ('that', 'ADP'), ('any', 'DET'), ('irregularities', 'NOUN'), ('took', 'VERB'), ('place', 'NOUN'), ('.', '.')], [('The', 'DET'), ('jury', 'NOUN'), ('further', 'ADV'), ('said', 'VERB'), ('in', 'ADP'), ('term-end', 'NOUN'), ('presentments', 'NOUN'), ('that', 'ADP'), ('the', 'DET'), ('City', 'NOUN'), ('Executive', 'ADJ'), ('Committee', 'NOUN'), (',', '.'), ('which', 'DET'), ('had', 'VERB'), ('over-all', 'ADJ'), ('charge', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('election', 'NOUN'), (',', '.'), ('``', '.'), ('deserves', 'VERB'), ('the', 'DET'), ('praise', 'NOUN'), ('and', 'CONJ'), ('thanks', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('City

In [3]:
tagged_corpus = nltk.corpus.brown.tagged_sents(tagset="universal")[:10_000]
tagged_corpus

[[('The', 'DET'), ('Fulton', 'NOUN'), ('County', 'NOUN'), ('Grand', 'ADJ'), ('Jury', 'NOUN'), ('said', 'VERB'), ('Friday', 'NOUN'), ('an', 'DET'), ('investigation', 'NOUN'), ('of', 'ADP'), ("Atlanta's", 'NOUN'), ('recent', 'ADJ'), ('primary', 'NOUN'), ('election', 'NOUN'), ('produced', 'VERB'), ('``', '.'), ('no', 'DET'), ('evidence', 'NOUN'), ("''", '.'), ('that', 'ADP'), ('any', 'DET'), ('irregularities', 'NOUN'), ('took', 'VERB'), ('place', 'NOUN'), ('.', '.')], [('The', 'DET'), ('jury', 'NOUN'), ('further', 'ADV'), ('said', 'VERB'), ('in', 'ADP'), ('term-end', 'NOUN'), ('presentments', 'NOUN'), ('that', 'ADP'), ('the', 'DET'), ('City', 'NOUN'), ('Executive', 'ADJ'), ('Committee', 'NOUN'), (',', '.'), ('which', 'DET'), ('had', 'VERB'), ('over-all', 'ADJ'), ('charge', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('election', 'NOUN'), (',', '.'), ('``', '.'), ('deserves', 'VERB'), ('the', 'DET'), ('praise', 'NOUN'), ('and', 'CONJ'), ('thanks', 'NOUN'), ('of', 'ADP'), ('the', 'DET'), ('City

In [100]:
tagged_corpus2 = nltk.corpus.brown.tagged_sents(tagset="universal")[:5]
tagged_corpus2

[[('The', 'DET'),
  ('Fulton', 'NOUN'),
  ('County', 'NOUN'),
  ('Grand', 'ADJ'),
  ('Jury', 'NOUN'),
  ('said', 'VERB'),
  ('Friday', 'NOUN'),
  ('an', 'DET'),
  ('investigation', 'NOUN'),
  ('of', 'ADP'),
  ("Atlanta's", 'NOUN'),
  ('recent', 'ADJ'),
  ('primary', 'NOUN'),
  ('election', 'NOUN'),
  ('produced', 'VERB'),
  ('``', '.'),
  ('no', 'DET'),
  ('evidence', 'NOUN'),
  ("''", '.'),
  ('that', 'ADP'),
  ('any', 'DET'),
  ('irregularities', 'NOUN'),
  ('took', 'VERB'),
  ('place', 'NOUN'),
  ('.', '.')],
 [('The', 'DET'),
  ('jury', 'NOUN'),
  ('further', 'ADV'),
  ('said', 'VERB'),
  ('in', 'ADP'),
  ('term-end', 'NOUN'),
  ('presentments', 'NOUN'),
  ('that', 'ADP'),
  ('the', 'DET'),
  ('City', 'NOUN'),
  ('Executive', 'ADJ'),
  ('Committee', 'NOUN'),
  (',', '.'),
  ('which', 'DET'),
  ('had', 'VERB'),
  ('over-all', 'ADJ'),
  ('charge', 'NOUN'),
  ('of', 'ADP'),
  ('the', 'DET'),
  ('election', 'NOUN'),
  (',', '.'),
  ('``', '.'),
  ('deserves', 'VERB'),
  ('the', 'DET'),

In [10]:
### fun to count repeated elements in list
def count_ngrams(lst):
    element_count = {}
    for item in lst:
        if item in element_count:
            element_count[item] += 1
        else:
            element_count[item] = 1
    return element_count

In [95]:
## use corpus 2 t reduce

# generate list with all POS from corpus
POS_list = []
for i in tagged_corpus2:
    POS_list += [tup[1] for tup in i]

In [97]:
# build dictioanary of counts of each POS
POS_counts = count_ngrams(POS_list)
# list of POS in corpus from dictionary POS_counts
list_pos = list(POS_counts.keys())
# list of POS counts from dictionary POS_counts
list_counts_pos = list(POS_counts.values())
# build list of probabilites out of counts
ts = sum(list_counts_pos)
pi = [c / ts for c in list_counts_pos]

In [98]:
# print pretty
print(POS_list)
print(POS_counts)
print("orden pi:", list_pos)
print(list_counts_pos)
print(pi)
print("suma de probs en pi:", sum(pi))

['DET', 'NOUN', 'NOUN', 'ADJ', 'NOUN', 'VERB', 'NOUN', 'DET', 'NOUN', 'ADP', 'NOUN', 'ADJ', 'NOUN', 'NOUN', 'VERB', '.', 'DET', 'NOUN', '.', 'ADP', 'DET', 'NOUN', 'VERB', 'NOUN', '.', 'DET', 'NOUN', 'ADV', 'VERB', 'ADP', 'NOUN', 'NOUN', 'ADP', 'DET', 'NOUN', 'ADJ', 'NOUN', '.', 'DET', 'VERB', 'ADJ', 'NOUN', 'ADP', 'DET', 'NOUN', '.', '.', 'VERB', 'DET', 'NOUN', 'CONJ', 'NOUN', 'ADP', 'DET', 'NOUN', 'ADP', 'NOUN', '.', 'ADP', 'DET', 'NOUN', 'ADP', 'DET', 'DET', 'NOUN', 'VERB', 'VERB', '.', 'DET', 'NOUN', 'NOUN', 'NOUN', 'VERB', 'VERB', 'VERB', 'ADP', 'NOUN', 'ADJ', 'NOUN', 'NOUN', 'NOUN', 'NOUN', 'PRT', 'VERB', 'NOUN', 'ADP', 'ADJ', '.', 'NOUN', '.', 'ADP', 'DET', 'ADJ', 'NOUN', 'DET', 'VERB', 'VERB', 'ADP', 'NOUN', 'NOUN', 'NOUN', 'NOUN', '.', '.', 'ADV', 'DET', 'ADJ', 'NOUN', 'ADP', 'ADJ', 'NOUN', 'VERB', 'VERB', '.', '.', 'DET', 'NOUN', 'VERB', '.', '.', 'ADP', 'DET', 'ADJ', 'NOUN', 'ADP', 'DET', 'NOUN', '.', 'DET', 'NOUN', 'ADP', 'NOUN', 'CONJ', 'DET', 'NOUN', 'ADP', 'DET', 'NOUN', 

In [105]:
# matrix a

## build dict of transition counts
# function to build bigrams
n_grams = [tuple(POS_list[i : i + 2]) for i in range(len(POS_list) - 1)]
# function to count bigrams, stores tuple of bigram as keys and repetition count as value---
d_pos_counts = count_ngrams(n_grams)

## build matrix
# build cols for matrix according to order of pi
unique_pos2 = list_pos
# build empty matix with rows and cols using pos order from pi
matrix_a = np.zeros((len(unique_pos2), len(unique_pos2)))

# Populate the matrix with values from the dictionary
for (pos1, pos2), count in d_pos_counts.items():
    matrix_a[unique_pos2.index(pos1)][unique_pos2.index(pos2)] = count

# Display the matrix
print(unique_pos2)
print(matrix_a)

['DET', 'NOUN', 'ADJ', 'VERB', 'ADP', '.', 'ADV', 'CONJ', 'PRT', 'PRON']
[[ 1. 18.  3.  2.  0.  0.  0.  0.  0.  0.]
 [ 2. 13.  4.  8. 11. 10.  1.  3.  1.  0.]
 [ 0.  9.  0.  0.  1.  2.  0.  2.  0.  0.]
 [ 1.  3.  2.  6.  4.  4.  0.  0.  0.  1.]
 [10.  7.  3.  0.  0.  0.  0.  0.  0.  0.]
 [ 7.  1.  0.  2.  4.  6.  1.  0.  0.  0.]
 [ 1.  0.  1.  1.  0.  0.  0.  0.  0.  0.]
 [ 1.  2.  1.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]


In [107]:
# build matrix B
## build list of only tuples of word-POS from tagged_corpus2
list_wp = [tuple_item for sublist in tagged_corpus2 for tuple_item in sublist]
# count bigrams, stores tuple of bigram as keys and repetition count as value---
d_wp_co = count_ngrams(list_wp)

# use dic pos_counts to calulate probability of  each  word-pos/pos
pwp = [value / POS_counts[pos] for (word, pos), value in d_wp_co.items()]
print(pwp)
## build matrix

[0.16666666666666666, 0.03773584905660377, 0.018867924528301886, 0.07142857142857142, 0.018867924528301886, 0.19047619047619047, 0.018867924528301886, 0.041666666666666664, 0.018867924528301886, 0.45, 0.018867924528301886, 0.07142857142857142, 0.03773584905660377, 0.09433962264150944, 0.047619047619047616, 0.2727272727272727, 0.041666666666666664, 0.018867924528301886, 0.2727272727272727, 0.15, 0.041666666666666664, 0.03773584905660377, 0.047619047619047616, 0.018867924528301886, 0.22727272727272727, 0.07547169811320754, 0.3333333333333333, 0.2, 0.018867924528301886, 0.018867924528301886, 0.5, 0.03773584905660377, 0.07142857142857142, 0.018867924528301886, 0.22727272727272727, 0.125, 0.09523809523809523, 0.07142857142857142, 0.018867924528301886, 0.047619047619047616, 0.018867924528301886, 0.8, 0.018867924528301886, 0.018867924528301886, 0.05, 0.018867924528301886, 0.14285714285714285, 0.047619047619047616, 0.018867924528301886, 0.018867924528301886, 0.047619047619047616, 0.04761904761

In [109]:
len(list_wp)
len(pwp)

95